# -*- coding: utf-8 -*-
"""Weather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cj9n1LrbW0WpgBX0um9CB8Qjt6PMimyd
"""

{
  "coord": {
    "lon": -122.08,
    "lat": 37.39
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "clear sky",
      "icon": "01d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 282.55,
    "feels_like": 281.86,
    "temp_min": 280.37,
    "temp_max": 284.26,
    "pressure": 1023,
    "humidity": 100
  },
  "visibility": 16093,
  "wind": {
    "speed": 1.5,
    "deg": 350
  },
  "clouds": {
    "all": 1
  },
  "dt": 1560350645,
  "sys": {
    "type": 1,
    "id": 5122,
    "message": 0.0139,
    "country": "US",
    "sunrise": 1560343627,
    "sunset": 1560396563
  },
  "timezone": -25200,
  "id": 420006353,
  "name": "Mountain View",
  "cod": 200
  }

r = requests.get('https://imgs.xkcd.com/comics/alternative_literature.png')
print (dir(r))

r = requests.get('https://imgs.xkcd.com/comics/alternative_literature.png')
print(help(r))

r = requests.get('https://imgs.xkcd.com/comics/alternative_literature.png')
print(r.content)

r = requests.get('https://imgs.xkcd.com/comics/alternative_literature.png')
print(r.text)

import requests
r = requests.get('https://imgs.xkcd.com/comics/alternative_literature.png')
with open('comic.png', 'wb') as f:
  f.write(r.content)

import requests
#import os
from datetime import datetime

api_key = '266c9022bb6e696b530e8879d2f5450e'
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

report= open('weather2.txt','w')


report.write ("-------------------------------------------------------------"+'\n')
report.write("Weather Stats for - {}  || {}".format(location.upper(), date_time)+ '\n')
report.write("-------------------------------------------------------------" + '\n')

report.write("Current temperature is: {:.2f} deg C".format(temp_city) +'\n')
report.write("Current weather desc  :"+ format(weather_desc) + '\n')
report.write("Current Humidity      :"+ format(hmdt) + '%' + '\n')
report.write("Current wind speed    :"+ format(wind_spd) +'kmph')

report.close()